name: awsini
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: any
  permission_handler: any
  device_info_plus: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_downloader: ^1.8.0+1
  device_info_plus: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/wallpaper1.png
    - assets/wallpaper2.png
    - assets/wallpaper3.png
    - assets/wallpaper4.png
