name: awsini
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.006

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: any
  permission_handler: any
  device_info_plus: any
  flutter_downloader: ^1.8.0+1
  file_picker: ^5.3.1
  path: ^1.8.3
  flutter_svg: ^1.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  image_gallery_saver: ^2.0.3
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.0
  firebase_storage: ^12.3.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  skeletonizer: ^1.4.2
  carousel_slider: ^5.0.0
  provider: ^6.0.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.1.0
  package_info_plus: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/icons/

    - assets/splash.png
    - assets/splash_android12.png

    - assets/wallpaper8_detail.png
    - assets/wallpaper9_detail.png
    - assets/low-rez-calligraphy.png
    - assets/calligrapher-desktop.png
    - assets/calligraphy-conversion.png
